### ISSUE TITLE
Interest in contributing to the repo

### ISSUE THREAD

**Issue by dustin-nguyen-qil** [wangxiao5791509/Cloth_Change_Person_reID_Paper_List#5]
Hi,

I am actively working on Cloth-Changing Re-ID. As I am staying very up-to-date to this topic, I would like to serve as a contributor to this repo to enhance research attention on this interesting topic. 

I would appreciate your consideration.

Thanks,
Dustin

**Comment by wangxiao5791509** [comment]
@dustin-nguyen-qil  Hi, thanks for your attention. No problem.

**Comment by dustin-nguyen-qil** [comment]
Can you add me as a contributor to the repo?

**Comment by wangxiao5791509** [comment]
@dustin-nguyen-qil  I have invited you to join this project.

**Comment by dustin-nguyen-qil** [comment]
I have accepted the invitation. Thanks.
